#%RAML 1.0 NamedExample
value:
  metric_type: "heart_rate"
  unit: "bpm"
  sum_value: 14532.0
  average_value: 145.3
  minimum_value: 98.0
  maximum_value: 183.0
  start_time: 2024-01-13T10:30:30-04:00
  end_time: 2024-01-13T10:48:56-04:00