#%RAML 1.0 DataType
type: object
description: Nutritional composition per 100g of food.
properties:
  energyKcal?: number|nil
  proteinG?: number | nil
  carbohydratesG?: number | nil
  dietaryFiberG?: number | nil
  sugarsG?: number | nil
  totalFatG?: number | nil
  saturatedFatG?: number | nil
  sodiumMg?: number | nil
  potassiumMg?: number | nil
  calciumMg?: number | nil
  ironMg?: number | nil
  vitaminCMg?: number | nil
  vitaminDMcg?: number | nil
  vitaminB12Mcg?: number | nil
  magnesiumMg?: number | nil
  zincMg?: number | nil
