<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>cebc8f976-c342-4bb4-9666-f6207f92deac</groupId>
	<artifactId>nutrisense</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>nutrisense</name>

	<modules>
		<module>system-apis/wearable-sys-api</module>
		<module>system-apis/nutrition-sys-api</module>
		<module>system-apis/meal-log-sys-api</module>
		<module>system-apis/userprofile-sys-api</module>
		<module>system-apis/notification-sys-api</module>
		<module>process-apis/daily-insight-process-api</module>
		<module>process-apis/trend-analysis-process-api</module>
		<module>experience-apis/personal-dashboard-exp-api</module>
		<module>experience-apis/coach-provider-exp-api</module>
	</modules>
</project>