#%RAML 1.0 Library
usage: NutriSense wearable domain types for use across NutriSense API specs.

types:
  PointMetric: !include point-metric-type.raml
  SleepSession: !include sleep-session-type.raml
  WorkoutStatistics: !include workout-statistics-type.raml
  Workout: !include workout-type.raml
  WearableIngest: !include wearable-ingest-type.raml
  PointMetricSummary: !include point-metric-summary-type.raml
  SleepSessionSummary: !include sleep-session-summary-type.raml
  WorkoutSummary: !include workout-summary-type.raml
  WearablesIngestResponse: !include wearable-ingest-response-type.raml
  WearableSummaryResponse: !include wearable-summary-response-type.raml