#%RAML 1.0 DataType
type: object
description: Dietary classification labels for this food.
properties:
  isVegan?: boolean | nil
  isVegetarian?: boolean | nil
  isHalal?: boolean | nil
  isKosher?: boolean | nil
  isGlutenFree?: boolean | nil