<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>cb90cdfe-fcc1-4bdc-a401-36bff2203ef6</groupId>
		<artifactId>nutrisense</artifactId>
		<version>1.0.0-SNAPSHOT</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>

	<artifactId>wearable-sys-api</artifactId>
	<packaging>mule-application</packaging>
	<name>wearable-sys-api</name>

	<build>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<configuration>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.postgresql</groupId>
							<artifactId>postgresql</artifactId>
						</sharedLibrary>
					</sharedLibraries>
					<cloudHub2Deployment>
						<uri>https://anypoint.mulesoft.com</uri>
						<provider>MC</provider>
						<environment>${env}</environment>
						<target>Cloudhub-US-East-2</target>
						<applicationName>wearable-sys-api</applicationName>
						<businessGroupId>${ANYPOINT_ORG_ID}</businessGroupId>
						<connectedAppClientId>${ANYPOINT_CLIENT_ID}</connectedAppClientId>
						<connectedAppClientSecret>${ANYPOINT_CLIENT_SECRET}</connectedAppClientSecret>
						<connectedAppGrantType>client_credentials</connectedAppGrantType>
						<replicas>1</replicas>
						<vCores>0.1</vCores>
						<deploymentSettings>
							<generateDefaultPublicUrl>true</generateDefaultPublicUrl>
						</deploymentSettings>
						<properties>
							<MULE_MASTER_KEY>${MULE_MASTER_KEY}</MULE_MASTER_KEY>
						</properties>
						<secureProperties>
							<MULE_MASTER_KEY>${MULE_MASTER_KEY}</MULE_MASTER_KEY>
						</secureProperties>
					</cloudHub2Deployment>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-sockets-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-db-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-validation-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-runner</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.munit</groupId>
			<artifactId>munit-tools</artifactId>
			<classifier>mule-plugin</classifier>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mule.weave</groupId>
			<artifactId>assertions</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>