user.profile.https.port=8084
user.profile.keystore.path=user-profile-sys-api-keystore.jks
user.profile.keystore.alias=user-profile-sys-api
user.profile.keystore.type=JKS
user.profile.keystore.password=![iqCgJ1MBE8Pb9r06C8dMEw==]
user.profile.keystore.keyPassword=![iqCgJ1MBE8Pb9r06C8dMEw==]

app.name=user-profile-sys-api
layer=system

nutrisense.db.host=localhost
nutrisense.db.port=5432
nutrisense.db.name=nutrisense
nutrisense.db.url=jdbc:postgresql://localhost:5432/nutrisense


nutrisense.db.driver=org.postgresql.Driver
nutrisense.db.password=![cBQ3mg1LhUBCck8LokGzzw==]
nutrisense.db.user=![xsRhB8xdSJh1ioOaXW5rVQ==]
