#%RAML 1.0 NamedExample
value:
  user_id: 1
  activity_type: "Running"
  start_time: "2023-01-20T07:00:00-04:00"
  end_time: "2023-01-20T07:45:00-04:00"
  source_device: "Health"
  duration: 2700
  duration_unit: "seconds"
  energy_burned: 420.5
  statistics:
    - metric_type: "heart_rate"
      unit: "bpm"
      sum_value: 14532.0
      average_value: 145.3
      minimum_value: 98.0
      maximum_value: 183.0
    - metric_type: "distance"
      unit: "miles"
      sum_value: 3.1
      average_value: null
      minimum_value: null
      maximum_value: null    