meals.https.port=8081
meals.keystore.path=meal-log-sys-api-keystore.jks
meals.keystore.alias=meal-log-sys-api
meals.keystore.type=JKS
meals.keystore.password=![iqCgJ1MBE8Pb9r06C8dMEw==]
meals.keystore.keyPassword=![iqCgJ1MBE8Pb9r06C8dMEw==]

app.name=meal-log-sys-api
nutrition.layer=system


nutrisense.db.host=localhost
nutrisense.db.port=5432
nutrisense.db.name=nutrisense
nutrisense.db.url=jdbc:postgresql://localhost:5432/nutrisense



nutrisense.db.driver=org.postgresql.Driver
nutrisense.db.password=![cBQ3mg1LhUBCck8LokGzzw==]
nutrisense.db.user=![xsRhB8xdSJh1ioOaXW5rVQ==]
