#%RAML 1.0 NamedExample
value: 
  totalResults: 3
  foods: 
    - foodId: 74778
      name: Oatmeal
      category: Cereals Grains and Pasta
      servingSizeG: 100
    - foodId: 747449
      name: Oatmeal, instant, plain, dry
      category: Cereal Grains and Pasta
      servingSizeG: 100
    - foodId: 747450
      name: Oatmeal, steel cut, dry
      category: Cereal Grains and Pasta
      servingSizeG: 100