#%RAML 1.0 NamedExample
displayName: Oatmeal Food Detail
value:
  foodId: 747448
  name: Oatmeal, regular and quick, unenriched, dry
  category: Cereal Grains and Pasta
  servingSizeG: 100
  source: USDA Foundation Foods
  nutrients:
    energyKcal: 389
    proteinG: 16.9
    carbohydratesG: 66.3
    dietaryFiberG: 10.6
    sugarsG: 0
    totalFatG: 6.9
    saturatedFatG: 1.21
    sodiumMg: 2
    potassiumMg: 429
    calciumMg: 54
    ironMg: 4.72
    vitaminCMg: 0
    vitaminDMcg: null
    vitaminB12Mcg: 0
    magnesiumMg: 177
    zincMg: 3.97
  allergens:
    containsGluten: null
    containsDairy: null
    containsNuts: null
    containsShellfish: null
    containsEggs: null
    containsSoy: null
  dietLabels:
    isVegan: null
    isVegetarian: null
    isHalal: null
    isKosher: null
    isGlutenFree: null