http.port=8083
http.protocol=HTTP
tls.keystore.path=wearable-sys-api-keystore.jks
tls.keystore.alias=wearable-sys-api
tls.keystore.type=JKS
tls.keystore.password=![iqCgJ1MBE8Pb9r06C8dMEw==]
tls.keystore.keyPassword=![iqCgJ1MBE8Pb9r06C8dMEw==]

app.name=wearable-sys-api
layer=system

nutrisense.db.port=5432
nutrisense.db.name=nutrisense
nutrisense.db.url=jdbc:postgresql://nutrisense-db.cc924g6k2jcf.us-east-1.rds.amazonaws.com:5432/nutrisense

nutrisense.db.driver=org.postgresql.Driver
nutrisense.db.user=![5+/22ee+1+8Bv35IBoNu2g==]
nutrisense.db.password=![aspp68nbZQi1WacSHVeeCA==]

apiId=21135431
