wearable.https.port=8083
wearable.keystore.path=wearable-sys-api-keystore.jks
wearable.keystore.alias=wearable-sys-api
wearable.keystore.type=JKS
wearable.keystore.password=![iqCgJ1MBE8Pb9r06C8dMEw==]
wearable.keystore.keyPassword=![iqCgJ1MBE8Pb9r06C8dMEw==]

app.name=wearable-sys-api
layer=system

nutrisense.db.host=localhost
nutrisense.db.port=5432
nutrisense.db.name=nutrisense
nutrisense.db.url=jdbc:postgresql://localhost:5432/nutrisense


nutrisense.db.driver=org.postgresql.Driver
nutrisense.db.password=![cBQ3mg1LhUBCck8LokGzzw==]
nutrisense.db.user=![xsRhB8xdSJh1ioOaXW5rVQ==]
