#%RAML 1.0 DataType
type: string
displayName: WearableMetricPreference
description: wearable metric types a user can select as preferred tracking metrics
enum:
  - heart_rate
  - sleep
  - steps
  - hrv
  - active_energy